version = "1"
#log_file = "serial-multiplexer.log"
tracing_filter = "serial_multiplexer=debug,serial_multiplexer::CW=info,serial_multiplexer::huge_data=info,serial_multiplexer::metrics=info"
threads = 4
watch_channels = false

[mode.host]
sink_type.windows_pipe.pipe_paths = ['\\.\pipe\myPipe1', '\\.\pipe\myPipe2', '\\.\pipe\myPipe3', '\\.\pipe\myPipe4']
sink_type.windows_pipe.unix_socket = 'serial_multiplexer.sock'
address_pairs = [
    {listener_address = "127.0.0.1:1235", target_address = "google.com:443"},
]
socks5_proxy = "127.0.0.1:2345"
http_proxy = "127.0.0.1:2355"
